name: CI Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '10'
              cache: 'npm'
              cache-dependency-path: ./frontend/package-lock.json

          - run: npm ci

  test:
      name: Test
      runs-on: ubuntu-latest
      needs: lint
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '10'
              cache: 'npm'
              cache-dependency-path: ./frontend/package-lock.json

          - run: npm ci